//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardValidation.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_info_tbl
    {
        public System.Guid card_info_id { get; set; }
        public Nullable<decimal> card_number { get; set; }
        public Nullable<decimal> card_expiry_month { get; set; }
        public Nullable<decimal> card_expiry_year { get; set; }
    }
}
